name: Build and Release
on:
  push:
    branches:
      - master
jobs:
  release:
    name: Build and Release
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
    steps:
      - name: Check out git repository
        uses: actions/checkout@v3.0.0
      - name: Install Node.js
        uses: actions/setup-node@v3.0.0
        with:
          node-version: '18'
      - name: Install Dependencies
        run: npm install
      - name: Build For Windows
        run: npm run deploy:win
        env:
          GITHUB_TOKEN: ${{ secrets.MARKDOWN_NOTE_SECRET }}
      - name: Cleanup Artifacts for Windows
        if: matrix.os == 'windows-latest'
        run: |
          npx rimraf "dist/!(*.exe)"
      - name: Upload artifacts
        uses: actions/upload-artifact@v3.0.0
        with:
          name: ${{ matrix.os }}
          path: dist
